# -*- coding: utf-8 -*-
"""faceid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Dmb2MFsbYBL2QE_Ih5Zi4bFJQt29bfj
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau

data_dir = r'/content/drive/MyDrive/60 ẢNH'
IMG_SIZE = 150
BATCH_SIZE = 32
EPOCHS = 70
model_path = "/content/drive/MyDrive/face_id_model.keras"

if not os.path.exists(data_dir):
    raise FileNotFoundError(f"The data directory '{data_dir}' does not exist. Please check your Google Drive path.")

print(f"Configuration loaded. Data directory: {data_dir}")

import os
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

data_dir = r'/content/drive/MyDrive/60 ẢNH'
IMG_SIZE = 150
BATCH_SIZE = 32

if not os.path.exists(data_dir):
    raise FileNotFoundError(f"Thư mục dữ liệu '{data_dir}' không tồn tại. Vui lòng kiểm tra đường dẫn Google Drive của bạn và đảm bảo nó đã được mount.")
print(f"Sử dụng thư mục dữ liệu: {data_dir}")

datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest',
    validation_split=0.2
)

try:
    train_generator = datagen.flow_from_directory(
        data_dir,
        target_size=(IMG_SIZE, IMG_SIZE),
        batch_size=BATCH_SIZE,
        class_mode='categorical',
        subset='training'
    )

    val_generator = datagen.flow_from_directory(
        data_dir,
        target_size=(IMG_SIZE, IMG_SIZE),
        batch_size=BATCH_SIZE,
        class_mode='categorical',
        subset='validation'
    )

    num_classes = train_generator.num_classes
    class_names = list(train_generator.class_indices.keys())

    print(f"\n Tìm thấy {num_classes} lớp (người): {class_names}")
    print(f"Train: {train_generator.samples} ảnh")
    print(f"Val: {val_generator.samples} ảnh")

except Exception as e:
    print(f"Lỗi khi tạo trình tạo dữ liệu: {e}")
    print("Vui lòng đảm bảo đường dẫn 'data_dir' của bạn là chính xác và chứa các thư mục con với hình ảnh cho mỗi lớp.")
    print("Ví dụ: /content/drive/MyDrive/YourFaceDataset/person_A/img1.jpg, /content/drive/MyDrive/YourFaceDataset/person_B/img2.jpg")
    raise

import os
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization

model_path = "/content/drive/MyDrive/face_id_model.keras" # Explicitly set to Drive path

if os.path.exists(model_path):
    print(f"\n Đã tìm thấy mô hình. Tải mô hình cũ để tiếp tục huấn luyện hoặc kiểm tra...")
    model = load_model(model_path)
    is_continue = True
else:
    print(f"\n Không tìm thấy mô hình cũ. Tạo mô hình mới...")
    model = Sequential([
        Conv2D(32, (3,3), activation='relu', input_shape=(IMG_SIZE, IMG_SIZE, 3)),
        BatchNormalization(),
        MaxPooling2D(2,2),

        Conv2D(64, (3,3), activation='relu'),
        BatchNormalization(),
        MaxPooling2D(2,2),

        Conv2D(128, (3,3), activation='relu'),
        BatchNormalization(),
        MaxPooling2D(2,2),

        Conv2D(256, (3,3), activation='relu'),
        BatchNormalization(),
        MaxPooling2D(2,2),

        Flatten(),
        Dense(256, activation='relu'),
        Dropout(0.4),
        Dense(num_classes, activation='softmax')
    ])
    is_continue = False

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau

model_path = "/content/drive/MyDrive/face_id_model.keras"
checkpoint = ModelCheckpoint(
    model_path,
    monitor='val_accuracy',
    save_best_only=True,
    verbose=1
)

reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=5,
    verbose=1
)

callbacks = [checkpoint, reduce_lr]
print("Callbacks defined.")

print(f"\nBắt đầu train {EPOCHS} epoch...")
history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=EPOCHS,
    callbacks=callbacks
)
print("Training complete!")

import cv2
import os
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model

model = load_model('/content/face_id_final_model.keras')

image_files = [
    '/content/thao.jpg',
    '/content/tran.PNG',
    '/content/tuan.jpg',
    '/content/tuy.jpg',
    '/content/uyen.jpg'
]

print(f"Testing model with {len(image_files)} images...")

num_images = len(image_files)
num_cols = 3
num_rows = (num_images + num_cols - 1) // num_cols

plt.figure(figsize=(num_cols * 4, num_rows * 4))
for i, image_path in enumerate(image_files):
    if not os.path.exists(image_path):
        print(f"Error: Image file not found at {image_path}. Skipping.")
        continue

    img = cv2.imread(image_path)
    if img is None:
        print(f"Error: Could not load image from {image_path}. Skipping.")
        continue

    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB);
    img_resized = cv2.resize(img_rgb, (IMG_SIZE, IMG_SIZE))
    img_normalized = img_resized / 255.0
    img_input = np.expand_dims(img_normalized, axis=0);
    predictions = model.predict(img_input)
    predicted_class_index = np.argmax(predictions, axis=1)[0]
    predicted_class_name = class_names[predicted_class_index]
    confidence = predictions[0][predicted_class_index] * 100
    plt.subplot(num_rows, num_cols, i + 1)
    plt.imshow(img_rgb)
    plt.title(f"Predicted: {predicted_class_name}\nConf: {confidence:.2f}%")
    plt.axis('off')

plt.tight_layout()
plt.show()
print("Image testing complete.")